### ISSUE TITLE
compilation errors while installing lpsolve from sources

### ISSUE THREAD

**Issue by thomascoutelen** [chandu-atina/lp_solve_python_3x#1]
**Got following errors**
/tmp/platform.c:3:1: warning: return type defaults to ���int��� [-Wimplicit-int]
 main(){printf("ux%d", (int) (sizeof(void *)*8));}
 ^~~~
In file included from ../lp_MDO.c:22:0:
../shared/commonlib.h:88:24: error: expected identifier or ���(��� before numeric constant
   #define FALSE        0
                        ^
In file included from ../lp_crash.c:21:0:
../shared/commonlib.h:88:24: error: expected identifier or ���(��� before numeric constant
   #define FALSE        0
                        ^
....

**leading to :** 

cc: error: lp_MDO.o: No such file or directory
cc: error: lp_crash.o: No such file or directory
cc: error: lp_wlp.o: No such file or directory
cc: error: lp_matrix.o: No such file or directory
cc: error: lp_mipbb.o: No such file or directory
cc: error: lp_MPS.o: No such file or directory
cc: error: lp_params.o: No such file or directory
cc: error: lp_presolve.o: No such file or directory
cc: error: lp_price.o: No such file or directory
cc: error: lp_pricePSE.o: No such file or directory
cc: error: lp_scale.o: No such file or directory
cc: error: lp_simplex.o: No such file or directory
cc: error: lp_SOS.o: No such file or directory
cc: error: lp_utils.o: No such file or directory

Is there a requirement for gcc ? (I use gcc (GCC) 7.1.1 20170621)

**Comment by chandu-atina** [comment]
Please provide your OS environment and sequence of steps you followed

**Comment by thomascoutelen** [comment]
Sorry the issue in not related to your work, but to LPSolver itself.
I fixed the issue by replacing 
#define FALSE 0
#define TRUE 0
by 
#define FFALSE 0
#define FTRUE 0
and FALSE/TRUE by FFALSE/FTRUE
in all included files.

I don't understand why I cannot define FALSE, but my C is very far away.

Thank you very much for your work !

**Comment by chandu-atina** [comment]
Good to hear that the issue is resolved !!
